services:
    wind.core.admin.post:
          class: Wind\AdminBundle\Admin\PostAdmin
          tags:
                - { name: sonata.admin, manager_type: orm, group: posts, label: posts }
          arguments: [null, Wind\ModelBundle\Entity\Post, ModelBundle:PostAdmin]