services:
    sonata.admin.post:
          class: Wind\AdminBundle\Admin\PostAdmin
          tags:
                - { name: sonata.admin, manager_type: orm, group: posts, label: posts }
          arguments: [null, Wind\ModelBundle\Entity\Post, SonataAdminBundle:CRUD]

    sonata.admin.generator:
          class: Wind\AdminBundle\Admin\GeneratorAdmin
          tags:
                - { name: sonata.admin, manager_type: orm, group: posts, label: generator }
          arguments: [null, Wind\ModelBundle\Entity\Generator, SonataAdminBundle:CRUD]