wind_model:
    resource: "@WindModelBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

#admin:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /admin
admin:
    resource: "@AdminBundle/Controller/"
    type: annotation
    prefix: /admin

#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin

wind_mail:
    pattern: "/mail"
    defaults: {_controller: WindCoreBundle:Post:mail}

_imagine:
    resource: .
    type:     imagine